GET http://localhost:3000/accounts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjIiLCJ1c2VybmFtZSI6IkppbSIsInJvbGUiOiJiYXNpYyIsImlhdCI6MTczMTg3NTU2OCwiZXhwIjoxNzMxODc2MTY4fQ.eqI0GmrFSYM1URRpBcuZjtr2ddHaKvh0jX5cmv9ayuw

###

GET http://localhost:3000/allAccounts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjEiLCJ1c2VybmFtZSI6IkjDqWxpbyIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTczMTg3NTgxOCwiZXhwIjoxNzMxODc2NDE4fQ.2pNmDzvSVuMs4VqBmdJY77ud02bDeBgbdorwzeuMpnA

###

POST http://localhost:3000/login
Content-Type: application/json

{
  "username": "Hélio"
}

###

POST http://localhost:3000/token
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjIiLCJ1c2VybmFtZSI6IkppbSIsImlhdCI6MTczMTg1MTY5Nn0.IAoT7TlqN8m69_1LBdSn52NnQmA5EDcn7EBvPdhtvQ4"
}

###

DELETE http://localhost:3000/logout
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjIiLCJ1c2VybmFtZSI6IkppbSIsImlhdCI6MTczMTg1MTY5Nn0.IAoT7TlqN8m69_1LBdSn52NnQmA5EDcn7EBvPdhtvQ4"
}