GET http://localhost:3000/accounts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiMiIsInVzZXJuYW1lIjoidXNlciIsInJvbGUiOiJ1c2VyIn0sImlhdCI6MTczMzA3MzU0NywiZXhwIjoxNzMzMDc0MTQ3fQ.PtW8I96rIUH1itOvihIdT2MdxF8A5Drczc7YaaexRQQ

###

GET http://localhost:3000/allAccounts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiMiIsInVzZXJuYW1lIjoidXNlciIsInJvbGUiOiJ1c2VyIn0sImlhdCI6MTczMzA3MzU0NywiZXhwIjoxNzMzMDc0MTQ3fQ.PtW8I96rIUH1itOvihIdT2MdxF8A5Drczc7YaaexRQQ

###

POST http://localhost:3000/login
Content-Type: application/json

{
  "username": "user"
}

###

POST http://localhost:3000/token
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiMiIsInVzZXJuYW1lIjoidXNlciIsInJvbGUiOiJ1c2VyIn0sImlhdCI6MTczMzA3MzU0N30.5Y1F_di-QKhnDntWjFufxKx1aOxHqkJ_HN2h2RxTqUY"
}

###

DELETE http://localhost:3000/logout
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiMiIsInVzZXJuYW1lIjoidXNlciIsInJvbGUiOiJ1c2VyIn0sImlhdCI6MTczMzA3MzU0N30.5Y1F_di-QKhnDntWjFufxKx1aOxHqkJ_HN2h2RxTqUY"
}